name: pretalx_schedule
description: A minimal Flutter application.
publish_to: 'none' # since it's not a package for pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  freezed_annotation: ^2.4.4
  go_router: ^14.6.2

  json_annotation: ^4.9.0
  logging: ^1.3.0
  provider: ^6.1.2

  shared_preferences: ^2.3.5

  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo_inverted.svg